---
# tasks file for Database


- name: "[lamp] - Create DB"
  mysql_db:
    name: "{{ mysql_db }}"
  become: yes

- name: "[lamp] - Create user"
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "*.*:ALL"
  become: yes


