---

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: 0440

- name:  Run the Composer installer
  command: creates="/usr/local/bin/composer" php /tmp/composer-setup.php --install-dir=/usr/local/bin/ --filename=composer

