
---
# tasks file for wordpress

- name: "[lamp] - install LAMP"
  include: install_stack_LAMP.yml
   
- name: "[lamp] - install Database"
  include: install_db.yml

- name: "[lamp] - install Wordpress"
  include: install_wordpress.yml

- name: "[lamp] - install Drupal"
  include: install_drupal.yml
